### ISSUE TITLE
Adobe Air error

### ISSUE THREAD

**Issue by kriswema** [WolverineFan/YNABLinuxInstall#1]
Hej,
after executing the script I'm getting this error. I don't think it's supposed to be this way.
![fullscreen_201306071529_terminal](https://f.cloud.github.com/assets/2233810/623934/e29e82c2-cf76-11e2-87dc-385f4fd63b44.png)

**Comment by PaBLoX-CL** [comment]
As of today: the package is `lib32-lcms2`, i guess that was a typo from @adampetrovic

**Comment by adampetrovic** [comment]
@PaBLoX-CL yep you're correct. Remember to enable to multilib repository in pacman.conf if you are on ArchLinux!
